apiVersion: training.eduk8s.io/v1alpha1
kind: WorkshopEnvironment
metadata:
  name: lab-kpack-testing
spec:
  workshop:
    name: lab-kpack-testing
  request:
    token: lab-kpack-testing
  session:
    username: eduk8s
    password: eduk8s
