apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-user
rules:
- apiGroups:
  - build.pivotal.io
  resources:
  - builds
  - builders
  - images
  - sourceresolvers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
