apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: registry
    spec:
      containers:
      - name: registry
        image: registry.hub.docker.com/library/registry:2.6.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
