apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        replicationcontroller: registry
    spec:
      containers:
      - image: registry.hub.docker.com/library/registry:2.6.1
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
