apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kpack-user
subjects:
- kind: ServiceAccount
  name: eduk8s
